var express = require("express");
const artistController = require("../../controllers/api/artist.controller");
var router = express.Router();
router.delete("/delete/many-artist", artistController.handleDeleteManyArtist);
router.post("/", artistController.handleCreateArtist);
router.delete("/:id", artistController.handleDeleteArtist);
router.get("/", artistController.handleGetAllArtist);
router.get("/profile-artist", artistController.handleProfileArtist);
router.put("/", artistController.handleEditArtist);
module.exports = router;
