var express = require('express');
var router = express.Router();
var authController = require('../../controllers/api/auth.controller');
var verifyToken = require('../../middlewares/verifyToken');
router.post('/sign-in', authController.handleLogin);
router.post('/token', verifyToken, authController.handleCheckToken);
router.post('/sign-up', authController.handleRegister);
router.get('/logout', verifyToken, authController.handleLogout);
router.post('/refresh-token', authController.handleRefreshToken);
module.exports = router;